Fund manager votes user guide
tumelohq/documentation pull request #42
Opened 2022-01-20 18:07 UTC by wycslingtum

Adding fund manager votes user guide

2022-01-20 20:56 UTC, KenxinKun requested changes

2022-01-20 20:56 UTC, KenxinKun commented on Stewardship/Fund_Manager_Votes.md
> +This guide explains how to obtain the voting information for a given fund manager. Tumelo collects fund manager voting information, including those votes the fund manager has identified as [significa
```suggestion
This guide explains how to obtain the voting information for a given fund manager. Tumelo collects fund manager voting information, including those votes the fund manager has identified as [significant](#definitions) on a regular basis, direct from the fund managers. The frequency with which voting information is updated varies between fund managers, but most provide updates at least once every three months. Please contact your Tumelo account manager if you require further information.
```

2022-01-20 20:57 UTC, KenxinKun commented on Stewardship/Fund_Manager_Votes.md
> +* Your habitat must be subscribed to one or more composite instruments. _The fund manager information and voting information that is available to you will depend on the composite instruments your hab
Do we use the term `composite instruments` outside of Tumelo or do we prefer `funds`?

2022-01-20 21:00 UTC, KenxinKun commented on Stewardship/Fund_Manager_Votes.md
> +        "habitatId": "{HABITAT_ID}",
`habitatId` is no longer required (since we allowed users to be multi-habitat) ref: https://docs.tumelo.com/#tag/Authentication

2022-01-21 14:47 UTC, wycslingtum commented on Stewardship/Fund_Manager_Votes.md
> +* Your habitat must be subscribed to one or more composite instruments. _The fund manager information and voting information that is available to you will depend on the composite instruments your hab
The rest of the guide refer to composite instruments, so I think this is consistent for now

2022-01-21 15:00 UTC, merged